<?php
$ticket = $block->getTicket();
?>

<?php if(!empty($ticket)) : ?>
    <div class="page-title-wrapper">
        <h1 class="page-title">
            <span class="base"><?= $ticket->getSubject() ?></span>
        </h1>
        <?php if($ticket->getTicketStatus() == 1) : ?>
            <span class="order-status">Active</span>
            <a href="<?= $block->getUrl('support/tickets/close', ['id' => $ticket->getId()]) ?>"><?= __('Close ticket') ?></a>
        <?php else : ?>
            <span class="order-status">Closed</span>
        <?php endif; ?>
        <div class="order-date">
            <date><?= date('d M Y, H:i', strtotime($ticket->getCreatedAt())) ?></date>
        </div>
    </div>

    <div class="ticket-details page-footer">
        <h3><?= $ticket->getMessage() ?></h3>
        <hr>
        <div class="ticket-replies-wrapper">
            <small><?= __('Ticket replies:') ?></small>
            <?php foreach($block->getTicketReplies($ticket->getId()) as $reply) : ?>
                <div class="reply <?= ($reply['is_admin']) ? 'admin' : 'customer' ?>">
                    <p><?= $reply['message'] ?> - <small><?= date('d M Y, H:i', strtotime($reply['created_at'])) ?></small></p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
